### ISSUE TITLE
compton fails to start using this compon.conf file.

### ISSUE THREAD

**Issue by osgyan** [ARCHLabs/Archlabs-Other-Config-Files#1]
Error when reading configuration file "/home/liveuser/.config/compton.conf", line 57: syntax error

Please fix and let me know.

**Comment by erikdubois** [comment]
not sure what your error was but i changed compton to work properly 
I kept glx as backend rather than xrender
inactive-dim has been hashtagged out - this solves the issue of having a shadow round conky aureola logo
delete line in fade-exclude to fix the same issue of a shadow round conky aureola conky
test this config out

**Comment by erikdubois** [comment]
@osgyan it is indeed line 57 that I have deleted now. So your error will be fixed now

**Comment by toola69** [comment]
@
